### ISSUE TITLE
Can anyone provide an example of MemoryCache with a Json serializer

### ISSUE THREAD

**Issue by umeshkarthik** [App-vNext/Polly.Caching.Serialization.Json#5]

**Comment by reisenberger** [comment]
I am assuming this is resolved, given the question raised at #6.

I wrote an example in #7 but opted not to highlight it in the ReadMe, as this represents a more unusual Use Case.  Serialization with an underlying cache is usually used when values _must_ be serialized (for instance for transmitting across the wire to a distributed cache).  With an in-memory cache there is not normally the need for serialization - the cache simply holds references to the native objects.  Indeed, for simple static data, a serialized copy might occupy more memory than the original instance would have; and the deserialization cost is paid on every get.

Possible reasons for serializing/deserializing to JSON with MemoryCache could include:

+ to release references to the particular object instance being cached
+ to custom-omit parts of the object graph being serialized, in order to release references and/or not rehydrate those parts when serving the object from cache
+ to create an immutable snapshot of the object state

Happy for community feedback on whether users think the MemoryCache with JsonSerializer example is worth adding to the readme.
